### ISSUE TITLE
Some sensors need a permission to work in fastest mode in Android 12

### ISSUE THREAD

**Issue by ebraminio** [kylecorry31/andromeda#45]
I have't yet faced the issue with Trail Sense as it is still targetSdk = 30 but while switching to targetSdk = 31 please note that some of the sensor will need the permission HIGH_SAMPLING_RATE_SENSORS to work in SENSOR_DELAY_FASTEST mode or one can switch to SENSOR_DELAY_GAME anyway. My experience is except the deprecated sensor TYPE_ORIENTATION, the rest are like that and they give the following error:

```
    java.lang.SecurityException: To use the sampling rate of 0 microseconds, app needs to declare the normal permission HIGH_SAMPLING_RATE_SENSORS.
```

Which https://developer.android.com/guide/topics/sensors/sensors_overview#sensors-rate-limiting is the related part of the documentation.

**Comment by kylecorry31** [comment]
Hi, there is an open issue for this in Trail Sense, my preference is for consuming apps to request that rather than Andromeda (since you can override the default sampling rate). I'll think this over, but I'm pretty sure I'm going to close this issue in favor of the Trail Sense one 

I'll also double check the sensors here to make sure the rate is customizable.

**Comment by ebraminio** [comment]
Oh, so let me close this one as I just wanted to notify you about this and no more, thanks :)
